### ISSUE TITLE
Chef 13 warning - you must use 'provides' to use the resource's DSL

### ISSUE THREAD

**Issue by adamfranco** [irvingpop/cookbook_versions#1]
Thanks for implementing this very useful cookbook. I just notice that `chef-client` version 12.9.41 is reporting the following errors when using this cookbook.

```
Recipe: cookbook_versions::default
  * cookbook_versions[pool] action create[2016-05-05T14:10:25-04:00] WARN: Class Chef::Provider::CookbookVersions does not declare 'provides :cookbook_versions'.
[2016-05-05T14:10:25-04:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.
```

**Comment by irvingpop** [comment]
Thanks @adamfranco for reporting that!    If you have a minute, could you please submit a PR that inserts that suggested code line [here](https://github.com/irvingpop/cookbook_versions/blob/master/libraries/cookbook_versions_provider.rb#L8) ?
