### ISSUE TITLE
Cookbooks without recipes in runlist aren't included.

### ISSUE THREAD

**Issue by adamfranco** [irvingpop/cookbook_versions#3]
I use several cookbooks like [ssh_authorized_keys](https://supermarket.chef.io/cookbooks/ssh_authorized_keys) that provide resources which are called from other recipes, but do not have their own recipes in the run-list. While they are in use and have their resource code run, they don't show up in the list provided by cookbook_versions because cookbook_versions is only looking at `run_context.loaded_recipes`.

Is there a reason to not to record all cookbooks in the `run_context.cookbook_collection`? I'll submit a PR that includes them all, but am open to the possibility of solving this issue a different way if there are reasons not to include everything in the cookbook_collection blindly.

**Comment by irvingpop** [comment]
New version 0.3.0 uploaded to supermarket:  https://supermarket.chef.io/cookbooks/cookbook_versions
